name: Close BTC Wednesday

on:
  schedule:
    - cron: "0 0 * * 4"   # Thursday 00:00 UTC
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run  Close Script
        run: python buy.py
        env:
          HL_SECRET: ${{ secrets.HL_SECRET }}
          HL_WALLET: ${{ secrets.HL_WALLET }}